[build]
  base = "artifacts/oncopatologia-2026"
  command = "pnpm install --prod=false --frozen-lockfile=false && NODE_ENV=production BASE_PATH=/ pnpm run build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"
  BASE_PATH = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
