// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/onco-redesign/Biopulse.tsx": () => import("../components/mockups/onco-redesign/Biopulse.tsx"),
  "./components/mockups/onco-redesign/CosmosOscuro.tsx": () => import("../components/mockups/onco-redesign/CosmosOscuro.tsx")
};
